matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-precise-4.0
          packages:
            - clang-4.0
      env:
        - MATRIX_EVAL="CC=clang-4.0 && CXX=clang++-4.0"

        
language: c++

dist: trusty
sudo: required
group: edge
warnings_are_errors: false

env:
  global:
    - POCL_LLVM_VERSION=3.8
    - POCL_LLVM_CONFIG=/usr/lib/llvm-${POCL_LLVM_VERSION}/bin/llvm-config
    - POCL_CXX_COMPILER=/usr/lib/llvm-${POCL_LLVM_VERSION}/bin/clang++
    - POCL_C_COMPILER=/usr/lib/llvm-${POCL_LLVM_VERSION}/bin/clang

compiler:
  - g++
  
before_install:
  - HOMEDIR="$PWD"
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq -y
  - sudo apt-get install -qq -y --force-yes opencl-headers g++-4.8 cmake git libtool libhwloc-dev wget g++ pkg-config libpthread-stubs0-dev clang-4.0 lldb-4.0 libclang-4.0-dev
  - export CXX="g++-4.8"
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 90
  
install:
  - |
    cd ..
    git clone -b release_1_0 https://github.com/pocl/pocl.git pocl
    cd pocl
    mkdir build
    cd build
    cmake -DWITH_LLVM_CONFIG=${POCL_LLVM_CONFIG} ..
    make
    sudo make install
  - cd $HOMEDIR
  - sudo ldconfig
  
  
script:
 - g++ -o clDeviceQuery clDeviceQuery.cpp -lOpenCL
 - ./clDeviceQuery

notifications:
  email:
    on_success: change
    on_failure: change
